### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by jersobh** [mrmakeit/HTML5-Webcaster#1]
Express
500 Error: /home/jeff/HTML5-Webcaster-master/views/control.jade:28 26| var first=true; 27| function startStream(){ > 28| socket.emit('start stream'); 29| } 30| function stopStream(){ 31| socket.emit('start stream'); unexpected text ; }

**Comment by Faeranne** [comment]
I'll look into it.

**Comment by Faeranne** [comment]
Forgot how old this project was.  I'll update the package.json to the required versions of jade and socket.io, but I do not recommend using this unless you are willing to put in a fair bit of work.  It is certainly not usable right now.
